version: "3"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        env_file:
            - ./backend/.env
        volumes:
            - mongodb_data_container:/data/db
    backend:
        image: server
        container_name: backend
        env_file:
            - ./backend/.env
        build:
            context: ./backend
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/app
            - /app/node_modules
        environment:
            MONGODB_HOST: mongodb
        depends_on:
            - mongodb
    frontend:
        image: react
        container_name: client
        env_file:
            - ./frontend/.env
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        depends_on:
            - backend
volumes:
    mongodb_data_container: